nav:
 - 'Home': index.md
 - ':custom-sparkles: Review Modes': code-reviews/review-modes.md
 - ':custom-rocket: Get Started': code-reviews/get-started
 - ':custom-monitor: IDE Reviews': code-reviews/ide-reviews
 - ':custom-git: PR Reviews': code-reviews/pr-reviews
 - ':custom-folder: Repo Reviews': code-reviews/repo-reviews
 - ':custom-terminal: CLI': code-reviews/cli
 - ':custom-database: External Knowledge': code-reviews/external-knowledge
 - ':custom-settings: Configuration': code-reviews/configuration
 - ':custom-history: Changelog': code-reviews/changelogs.md
 - ':custom-faq: FAQ': code-reviews/faq.md
 - ':custom-alert: Troubleshooting': code-reviews/troubleshooting.md
 - ':custom-file: Reference': code-reviews/reference.md
 - 'AI Resources': ai-resources.md
