title: MCP
hide: true
nav:
  - 'Overview': overview.md
  - 'Get started': get-started.md
  - 'Client integrations': client-integrations.md
  - sdk-integrations
  - cloud
  - 'Self-hosted MCP': self-hosted.md
  - 'Tools': tools.md