nav:
  - 'Quickstart': quickstart.md
  - ':simple-github: GitHub': github.md
  - ':simple-gitlab: GitLab': gitlab.md
  - ':simple-bitbucket: Bitbucket': bitbucket.md
  - ':material-microsoft-azure-devops: Azure DevOps': azure-devops.md
