title: Code Reviews
hide: false
nav:
  - 'Review modes': review-modes.md
  - 'Get started': get-started
  - 'Vibe Coding': agent-mode
  - 'Manual Coding': instant-ide-mode
  - 'Configuration': configuration
  - 'FAQ': faq.md
  - 'Reference': reference
  - 'How to use activation codes': activation-codes.md
