title: Code Reviews
hide: false
nav:
  - 'Overview': index.md
  - 'Installation': installation.md
  - 'Quick Start': quickstart.md
  - 'Tools reference': tools.md
  - 'Configuration': configuration
  - 'Examples': examples
  - 'FAQ': faq.md
  - 'How to use activation codes': activation-codes.md

