nav:
  - 'Review modes': review-modes.md
  - 'Get started': get-started
  - 'IDE Reviews': ide-reviews
  # - 'PR Reviews': pr-reviews
  - 'Repo Reviews': repo-reviews
  - 'CLI': cli
  - 'External Knowledge': external-knowledge
  - 'Configuration': configuration
  - 'Video library': video-library.md
  - 'FAQ': faq.md
  - 'Troubleshooting': troubleshooting.md
  - 'Reference': reference
