nav:
  - 'Review modes': review-modes.md
  - 'Get started': get-started
  - 'IDE reviews': ide-reviews
  - 'Repo reviews': repo-reviews
  - 'CLI': cli
  - 'Configuration': configuration
  - 'FAQ': faq.md
  - 'Troubleshooting': troubleshooting.md
  - 'Reference': reference
  - 'How to use activation codes': activation-codes.md
