nav:
  - 'Review modes': review-modes.md
  - 'Get started': get-started
  - 'Human-written code': instant-ide-mode
  - 'AI-generated code': agent-mode
  - 'Configuration': configuration
  - 'FAQ': faq.md
  - 'Troubleshooting': troubleshooting.md
  - 'Reference': reference
  - 'How to use activation codes': activation-codes.md
