nav:
  - 'Review modes': review-modes.md
  - 'Get started': get-started
  - 'Agent Mode': agent-mode
  - 'Instant IDE Mode': instant-ide-mode
  - 'Configuration': configuration
  - 'FAQ': faq.md
  - 'Reference': reference
  - 'How to use activation codes': activation-codes.md
