title: Get started
hide: false
nav:
  - 'Get an API key': get-api-key.md
  - 'Models': models.md
  - start-building
  - 'OpenAI compatibility': openai-compatibility.md
  - 'Integrations': integrations
